// <auto-generated />
using E2EApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E2EApplication.Migrations
{
    [DbContext(typeof(BookAPIContext))]
    partial class BookAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E2EApplication.Models.Book", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yearPublished")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            id = 1,
                            author = "George Orwell",
                            title = "Mount Fuji 1984",
                            yearPublished = "1949"
                        },
                        new
                        {
                            id = 2,
                            author = "Harper Lee",
                            title = "To Kill a Mocking,ird",
                            yearPublished = "1960"
                        },
                        new
                        {
                            id = 3,
                            author = "F. Scott Fitzgerald",
                            title = "The Great Gatsby",
                            yearPublished = "1925"
                        },
                        new
                        {
                            id = 4,
                            author = "Jane Austen",
                            title = "Pride and Prejudice",
                            yearPublished = "1813"
                        },
                        new
                        {
                            id = 5,
                            author = "J.D. Salinger",
                            title = "The Catcher in the Rye",
                            yearPublished = "1951"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
